language: python
sudo: false
python:
  - "2.7"
  - "3.4"
services:
- elasticsearch
before_script:
  - sleep 10
env:
  - DJANGO_REQUIREMENT="Django>=1.6,<1.7"
  - DJANGO_REQUIREMENT="Django==1.8"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $DJANGO_REQUIREMENT "elasticsearch>=1.6.0,<1.7.0" "django-haystack==2.4.0" django-modeltranslation django-parler flake8 --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script:
  - flake8
  - cd tests
  - ./manage.py test tests